version: '3.8'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-dev}
    container_name: veggievibe
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    networks:
      - app-network

  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
