parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Redis:
        class: Redis
        calls:
            - method: connect
              arguments:
                - '%env(REDIS_HOST)%'
                - '%env(int:REDIS_PORT)%'
                - '%env(int:REDIS_TIMEOUT)%'

    VeggieVibe\Shared\:
        resource: '../src/Shared'
        exclude:
            - 'Kernel.php'

    VeggieVibe\Fruit\:
        resource: '../src/Fruit'

    VeggieVibe\Vegetable\:
        resource: '../src/Vegetable'
