parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    VeggieVibe\Shared\:
        resource: '../src/Shared'
        exclude:
            - 'Kernel.php'

    VeggieVibe\Fruit\:
        resource: '../src/Fruit'

    VeggieVibe\Vegetable\:
        resource: '../src/Vegetable'